# Generated by Django 2.1 on 2020-02-03 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default=None, max_length=50)),
                ('slika', models.ImageField(default=None, upload_to='profile_pics')),
                ('adresa', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('misija', models.TextField(blank=True)),
                ('misija_en', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profili',
            },
        ),
    ]
