# Generated by Django 2.1 on 2020-03-21 01:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='misija',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='misija_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
