# Generated by Django 2.1 on 2020-02-03 13:10

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktuelnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=100)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Slika', models.ImageField(default=None, upload_to='profile_pics')),
                ('Datum_objave', models.DateTimeField(default=django.utils.timezone.now)),
                ('Kratak_opis', models.CharField(max_length=184)),
                ('Short_description', models.CharField(max_length=184)),
                ('Opis', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aktuelnosti',
            },
        ),
    ]
