# Generated by Django 2.1 on 2020-02-04 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0002_aktuelnost'),
    ]

    operations = [
        migrations.AddField(
            model_name='publikacija',
            name='Datum_objave',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
