# Generated by Django 2.1 on 2020-02-11 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0003_publikacija_datum_objave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArhivskiMaterijal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=100)),
                ('Ime_en', models.CharField(blank=True, max_length=100, null=True)),
                ('Slika', models.ImageField(default=None, upload_to='press_pics')),
                ('Kratak_opis', models.CharField(max_length=184)),
                ('Short_description', models.CharField(max_length=184)),
                ('Datum_objave', models.DateTimeField(default=django.utils.timezone.now)),
                ('Projekat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpi.Projekat')),
            ],
            options={
                'verbose_name_plural': 'Arhiva',
            },
        ),
        migrations.CreateModel(
            name='Izlozba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=100)),
                ('Ime_en', models.CharField(blank=True, max_length=100, null=True)),
                ('Slika', models.ImageField(default=None, upload_to='press_pics')),
                ('Kratak_opis', models.CharField(max_length=184)),
                ('Short_description', models.CharField(max_length=184)),
                ('Datum_objave', models.DateTimeField(default=django.utils.timezone.now)),
                ('Projekat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpi.Projekat')),
            ],
            options={
                'verbose_name_plural': 'Izlozbe',
            },
        ),
        migrations.AddField(
            model_name='pressclanak',
            name='Projekat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpi.Projekat'),
        ),
        migrations.AddField(
            model_name='publikacija',
            name='Projekat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpi.Projekat'),
        ),
        migrations.AlterField(
            model_name='fotografija',
            name='Projekat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpi.Izlozba'),
        ),
    ]
