# Generated by Django 2.1 on 2020-03-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0007_istorijskatura_ime_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istorijskatura',
            name='Ime_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
