# Generated by Django 2.1 on 2020-03-04 14:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0010_auto_20200303_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjekatPodkategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Projekti',
            },
        ),
        migrations.CreateModel(
            name='SadrzajProjekatPodkategorije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opis', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Podkategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpi.ProjekatPodkategorija')),
                ('Projekat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpi.Projekat')),
            ],
            options={
                'verbose_name_plural': 'Projekti',
            },
        ),
    ]
