# Generated by Django 2.1 on 2020-03-13 15:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0011_projekatpodkategorija_sadrzajprojekatpodkategorije'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projekatpodkategorija',
            options={'verbose_name_plural': 'Podkategorije Projekata'},
        ),
        migrations.AlterModelOptions(
            name='sadrzajprojekatpodkategorije',
            options={'verbose_name_plural': 'Sadržaji podkategorija projekata'},
        ),
        migrations.AddField(
            model_name='projekat',
            name='Fajl',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
