# Generated by Django 2.1 on 2020-03-17 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0013_projekatpodkategorija_ime_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='izlozba',
            name='Opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='izlozba',
            name='Opis_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
