# Generated by Django 2.1 on 2020-03-17 22:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0014_auto_20200317_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekat',
            name='Kratak_opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projekat',
            name='Kratak_opis_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
