# Generated by Django 2.1 on 2020-03-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0016_publikacija_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istaknuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=10)),
                ('Ime_en', models.CharField(max_length=10)),
                ('Slika', models.ImageField(upload_to='istaknuto')),
                ('Link_tekst', models.CharField(max_length=12)),
            ],
        ),
    ]
