# Generated by Django 2.1 on 2020-03-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0018_auto_20200321_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istaknuto',
            name='Ime',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='istaknuto',
            name='Ime_en',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='istaknuto',
            name='Link_tekst',
            field=models.CharField(max_length=20),
        ),
    ]
