# Generated by Django 2.1 on 2020-03-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0019_auto_20200321_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='istaknuto',
            name='Link_tekst_en',
            field=models.CharField(default='LEARN MORE', max_length=20),
        ),
    ]
