# Generated by Django 2.1 on 2020-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpi', '0021_prijava_tura'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoklip',
            name='Video_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
